package com.marta.logistika.controllerAdvice;

import com.marta.logistika.dto.ErrorMessage;
import com.marta.logistika.exception.checked.CheckedServiceException;
import com.marta.logistika.exception.unchecked.EntityNotFoundException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.ControllerAdvice;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.springframework.web.servlet.NoHandlerFoundException;

import javax.servlet.http.HttpServletRequest;
import java.util.Locale;


@ControllerAdvice
public class ExceptionHandlingControllerAdvice {

    private static final Logger LOGGER = LoggerFactory.getLogger(ExceptionHandlingControllerAdvice.class);

    /**
     * Provides custom error page for all unmapped requests and all resources not found
     *
     * @param e       incoming exception
     * @param uiModel model
     * @return path to jsp error page
     */
    @ExceptionHandler({NoHandlerFoundException.class, EntityNotFoundException.class})
    public String handleNoHandlerFoundException(final Exception e, Model uiModel) {
        LOGGER.warn(e.getMessage());
        ErrorMessage errorMessage = new ErrorMessage();
        errorMessage.setTitle("error.smthWentWrong");
        errorMessage.setMessage("error.resourceNotFound");
        uiModel.addAttribute("error", errorMessage);
        return "common/error";
    }


    /**
     * Provides error page for all exceptions generated by the application (if not processed otherwise)
     *
     * @param e       incoming exception
     * @param uiModel model
     * @param locale  user locale
     * @return path to jsp error page
     */
    @ExceptionHandler(CheckedServiceException.class)
    public String handleServiceException(final CheckedServiceException e, Model uiModel, Locale locale) {
//        LOGGER.error(e.getMessage(), e);
        ErrorMessage errorMessage = new ErrorMessage();
        errorMessage.setTitle("error.smthWentWrong");
        errorMessage.setMessage(e.getLocalizedMessage(locale));
        uiModel.addAttribute("error", errorMessage);
        return "common/error";
    }


    /**
     * Provides custom error page for all exceptions (if not processed otherwise)
     *
     * @param e       exception
     * @param request request which caused the exception
     * @param uiModel model
     * @return path to jsp error page
     */
    @ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
    @ExceptionHandler(Exception.class)
    public String handleThrowable(final Exception e, HttpServletRequest request, Model uiModel) {
        LOGGER.error(String.format("Request %s resulted in exception %s", request.getRequestURL(), e.getLocalizedMessage()));
        ErrorMessage errorMessage = new ErrorMessage();
        errorMessage.setTitle("error.smthWentWrong");
        errorMessage.setMessage("error.internalServerError");
        uiModel.addAttribute("error", errorMessage);
        return "common/error";
    }

}
